osx_image: xcode7.3
language: objective-c
script:
  - xctool test -project RATreeView/RATreeView.xcodeproj -scheme RATreeViewTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -project RATreeView/RATreeView.xcodeproj -scheme RATreeViewTests -sdk appletvsimulator ONLY_ACTIVE_ARCH=NO
